# ConfigMap - アプリケーション設定
# AWS ECSのタスク定義の環境変数に相当
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sample-app
  labels:
    app: sample-app
    component: config
data:
  # アプリケーション設定
  NODE_ENV: "development"
  APP_PORT: "3000"
  LOG_LEVEL: "info"
  
  # データベース設定（機密情報でない部分）
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "sampledb"
  
  # Redis設定
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # アプリケーション設定ファイル
  app.properties: |
    # サンプルアプリケーション設定
    app.name=K8s Sample App
    app.version=1.0.0
    app.description=AWS ECS管理者向けKubernetes学習アプリ
    
    # セッション設定
    session.timeout=3600
    session.secure=false
    
    # ログ設定
    log.format=json
    log.rotation=daily
