# ネームスペース定義
# AWS ECSのクラスター概念に近い、リソースの論理的な分離
apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
  labels:
    app: sample-app
    environment: development
  annotations:
    description: "サンプルWebアプリケーション用のネームスペース"
---
# リソースクォータ - ECSのサービス制限に相当
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sample-app-quota
  namespace: sample-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    services: "5"
    persistentvolumeclaims: "3"
