# Secret - 機密情報管理
# AWS ECSのタスク定義のシークレット、Parameter Storeに相当
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: sample-app
  labels:
    app: sample-app
    component: secrets
type: Opaque
data:
  # Base64エンコードされた値（実際のデプロイ時は適切な値に変更）
  # 注意: 本番環境では外部のシークレット管理ツール（AWS Secrets Manager等）を使用
  
  # データベース認証情報
  DB_USERNAME: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  
  # アプリケーションシークレット
  JWT_SECRET: bXktand0LXNlY3JldC1rZXk=  # my-jwt-secret-key
  SESSION_SECRET: c2Vzc2lvbi1zZWNyZXQtMTIz  # session-secret-123
  
  # API キー（例）
  EXTERNAL_API_KEY: YWJjZGVmZ2hpams=  # abcdefghijk

---
# TLS証明書用Secret（例）
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: sample-app
  labels:
    app: sample-app
    component: tls
type: kubernetes.io/tls
data:
  # 注意: 実際の証明書を使用する場合は適切な値に変更
  tls.crt: LS0tLS1CRUdJTi... # 証明書データ
  tls.key: LS0tLS1CRUdJTi... # 秘密鍵データ
