# 06-heavy-logger.yaml - 大量ログ出力によるローテーション学習用
apiVersion: v1
kind: Pod
metadata:
  name: heavy-logger
  labels:
    app: heavy-logger
    phase: basic-logging
spec:
  containers:
  - name: heavy-generator
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "大量ログ生成器を開始します（ログローテーション学習用）"
        counter=0
        while true; do
          # 長いログメッセージを生成してファイルサイズを増加
          padding=$(printf '%*s' 200 '' | tr ' ' 'x')
          echo "$(date) HEAVY_LOG #$counter: 大量のデータを含むログメッセージです。$padding"
          
          # より高頻度でログ出力
          counter=$((counter + 1))
          sleep 0.1
        done
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
  restartPolicy: Always
