# 02-multi-container.yaml - マルチコンテナPod
apiVersion: v1
kind: Pod
metadata:
  name: multi-logger
  labels:
    app: multi-logger
    phase: basic-logging
spec:
  containers:
  # メインアプリケーションコンテナ
  - name: app-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "アプリケーションコンテナが開始されました"
        counter=0
        while true; do
          echo "[APP] $(date): リクエスト処理 #$counter"
          if [ $((counter % 10)) -eq 0 ]; then
            echo "[APP] $(date): 定期メンテナンス実行"
          fi
          counter=$((counter + 1))
          sleep 5
        done
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
  
  # サイドカーコンテナ（ログ収集・監視用）
  - name: sidecar-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "サイドカーコンテナが開始されました"
        while true; do
          echo "[SIDECAR] $(date): システム監視中..."
          echo "[SIDECAR] $(date): メトリクス収集完了"
          sleep 8
        done
    resources:
      requests:
        memory: "16Mi"
        cpu: "25m"
      limits:
        memory: "32Mi"
        cpu: "50m"
  
  restartPolicy: Always
