# 07-crash-logger.yaml - クラッシュとログ履歴学習用
apiVersion: v1
kind: Pod
metadata:
  name: crash-logger
  labels:
    app: crash-logger
    phase: basic-logging
spec:
  containers:
  - name: crash-generator
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "クラッシュするアプリケーションを開始します"
        echo "開始時刻: $(date)"
        counter=0
        while [ $counter -lt 10 ]; do
          echo "$(date) 正常動作中... カウンター: $counter"
          counter=$((counter + 1))
          sleep 2
        done
        echo "$(date) ERROR: 致命的なエラーが発生しました！"
        echo "$(date) クラッシュします..."
        exit 1
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
  restartPolicy: Always
