# 08-namespace-logger.yaml - ネームスペース間ログ操作学習用
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-app
  namespace: logging-demo
  labels:
    app: namespace-app
    phase: basic-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namespace-app
  template:
    metadata:
      labels:
        app: namespace-app
        environment: demo
    spec:
      containers:
      - name: namespace-logger
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "ネームスペース: logging-demo でアプリケーション開始"
            echo "Pod名: $(hostname)"
            counter=0
            while true; do
              echo "[NAMESPACE:logging-demo] $(date): アプリケーション動作中 #$counter"
              
              # 環境固有のログ
              if [ $((counter % 10)) -eq 0 ]; then
                echo "[NAMESPACE:logging-demo] $(date): demo環境の定期チェック完了"
              fi
              
              counter=$((counter + 1))
              sleep 5
            done
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Pod
metadata:
  name: namespace-logger
  namespace: logging-demo
  labels:
    app: namespace-logger
    phase: basic-logging
spec:
  containers:
  - name: logger
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "専用ネームスペースでの単一Podログ学習"
        counter=0
        while true; do
          echo "[POD:namespace-logger] $(date): 単一Podログメッセージ #$counter"
          counter=$((counter + 1))
          sleep 7
        done
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
  restartPolicy: Always
