# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: monitoring-app
type: Opaque
data:
  # postgres
  username: cG9zdGdyZXM=
  # password123
  password: cGFzc3dvcmQxMjM=
  # monitoring_app
  database: bW9uaXRvcmluZ19hcHA=
