apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=  # 'password'をBase64エンコードした値
  another-secret: c2VjcmV0  # 'secret'をBase64エンコードした値

# このファイルはPostgreSQLのパスワードやその他の機密情報を管理するためのKubernetesシークレットを定義しています。
# Base64エンコードされた値を使用して、セキュリティを強化しています。