# PostgreSQL設定
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: monitoring-app
data:
  # PostgreSQL設定ファイル
  postgresql.conf: |
    # 接続とセキュリティ設定
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    
    # ログ設定（詳細なログ出力）
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/var/lib/postgresql/data/pg_log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_file_mode = 0644
    log_rotation_age = 1d
    log_rotation_size = 100MB
    
    # ログレベルとフィルタリング
    log_min_messages = info
    log_min_error_statement = error
    log_min_duration_statement = 100  # 100ms以上のクエリをログ出力
    
    # ログ内容設定
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_lock_waits = on
    log_statement = 'all'  # すべてのSQL文をログ出力
    log_temp_files = 0
    
    # パフォーマンス設定
    effective_cache_size = 256MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    
    # 日本語対応
    lc_messages = 'ja_JP.UTF-8'
    lc_monetary = 'ja_JP.UTF-8'
    lc_numeric = 'ja_JP.UTF-8'
    lc_time = 'ja_JP.UTF-8'
  
  # 初期化SQL
  init.sql: |
    -- データベース作成（既に存在する場合はスキップ）
    SELECT 'CREATE DATABASE monitoring_app'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'monitoring_app')\gexec
    
    -- monitoring_appデータベースに接続
    \c monitoring_app;
    
    -- usersテーブル作成
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(150) UNIQUE NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    
    -- インデックス作成
    CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
    CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);
    
    -- サンプルデータ挿入
    INSERT INTO users (name, email) VALUES
    ('山田太郎', 'yamada@example.com'),
    ('佐藤花子', 'sato@example.com'),
    ('田中一郎', 'tanaka@example.com'),
    ('鈴木美香', 'suzuki@example.com'),
    ('高橋健太', 'takahashi@example.com')
    ON CONFLICT (email) DO NOTHING;
    
    -- ログテーブル作成（アプリケーションログ用）
    CREATE TABLE IF NOT EXISTS app_logs (
        id SERIAL PRIMARY KEY,
        timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        level VARCHAR(10) NOT NULL,
        message TEXT NOT NULL,
        metadata JSONB,
        request_id VARCHAR(36),
        user_id INTEGER REFERENCES users(id)
    );
    
    CREATE INDEX IF NOT EXISTS idx_app_logs_timestamp ON app_logs(timestamp);
    CREATE INDEX IF NOT EXISTS idx_app_logs_level ON app_logs(level);
    CREATE INDEX IF NOT EXISTS idx_app_logs_request_id ON app_logs(request_id);
    
    -- 統計情報更新
    ANALYZE;
