apiVersion: batch/v1
kind: Job
metadata:
  name: init-postgres
spec:
  template:
    spec:
      containers:
      - name: init-postgres
        image: postgres:14
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        - name: POSTGRES_DB
          value: postgres
        command: ["sh", "-c", "psql -h my-postgres.default.svc.cluster.local -U postgres -d postgres -f /init/init.sql"]
        volumeMounts:
        - name: init-scripts
          mountPath: /init
      restartPolicy: OnFailure
      volumes:
      - name: init-scripts
        configMap:
          name: init-scripts-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS my_table (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL
    );