apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres
spec:
  instances: 1
  storage:
    size: 1Gi
  postgresql:
    username: postgres
    password: mysecretpassword
    database: postgres
  service:
    type: ClusterIP
  backup:
    enabled: true
    schedule: "0 2 * * *"  # 毎日午前2時にバックアップを実行
  monitoring:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
      metricsPath: /metrics
      port: metrics