# ServiceAccount 定義
# AWS ECS Task Role に相当するKubernetesの実行主体
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: security-demo
  labels:
    app: frontend
    role: web-service
  annotations:
    description: "フロントエンドアプリケーション用ServiceAccount"
    aws-ecs-equivalent: "ecs-frontend-task-role"
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: security-demo
  labels:
    app: backend
    role: api-service
  annotations:
    description: "バックエンドAPI用ServiceAccount"
    aws-ecs-equivalent: "ecs-backend-task-role"
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-admin-sa
  namespace: security-demo
  labels:
    app: database
    role: admin-service
  annotations:
    description: "データベース管理用ServiceAccount"
    aws-ecs-equivalent: "ecs-db-admin-task-role"
automountServiceAccountToken: true

---
# 制限された権限のServiceAccount（権限テスト用）
apiVersion: v1
kind: ServiceAccount
metadata:
  name: limited-sa
  namespace: security-demo
  labels:
    app: test
    role: limited-access
  annotations:
    description: "制限されたアクセス権限のテスト用ServiceAccount"
    aws-ecs-equivalent: "ecs-readonly-task-role"
automountServiceAccountToken: true
