# Demo Application Service
# AWS ECSのService DiscoveryやInternal Load Balancerに相当
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: gateway-demo
  labels:
    app: demo-app
    tier: frontend
  annotations:
    # AWS ECS比較: Service Discoveryの設定に相当
    description: "Service for demo application - targets backend pods"
spec:
  # サービスタイプ（AWS ECS比較：内部ロードバランサー相当）
  type: ClusterIP
  
  # セッションアフィニティ（AWS ALBのSticky sessionsに相当）
  sessionAffinity: None
  
  # Pod選択（AWS ECSのTaskに相当）
  selector:
    app: demo-app
  
  # ポート設定（AWS ECSのPort mappingに相当）
  ports:
  - name: http
    port: 80
    targetPort: http  # コンテナの名前付きポート
    protocol: TCP

---
# ヘルスチェック用のService（オプション）
apiVersion: v1
kind: Service
metadata:
  name: demo-service-headless
  namespace: gateway-demo
  labels:
    app: demo-app
    type: headless
  annotations:
    description: "Headless service for direct pod access"
spec:
  # ヘッドレスサービス（DNS-based service discovery）
  type: ClusterIP
  clusterIP: None
  
  selector:
    app: demo-app
  
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---
# LoadBalancer型Service（クラウド環境での代替案）
# AWS環境ではこちらも使用可能
# apiVersion: v1
# kind: Service
# metadata:
#   name: demo-service-lb
#   namespace: gateway-demo
#   annotations:
#     # AWS Load Balancer Controller用のアノテーション
#     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#     service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
# spec:
#   type: LoadBalancer
#   selector:
#     app: demo-app
#   ports:
#   - name: http
#     port: 80
#     targetPort: http
#     protocol: TCP
