# 複数環境のNamespace設定例
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: development
    team: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    team: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    environment: production
    team: frontend
