# Redis Service
# AWS ECSのサービスディスカバリに相当
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: sample-app
  labels:
    app: sample-app
    component: redis
    tier: cache
spec:
  type: ClusterIP  # クラスター内部からのみアクセス可能
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: sample-app
    component: redis
