# PostgreSQL 永続化ボリュームクレーム
# AWS ECSのEBSボリュームに相当
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: sample-app
  labels:
    app: sample-app
    component: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # ストレージクラス（環境に応じて調整）
  storageClassName: standard
