# Kubernetes学習ワークスペース - Markdown Server ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: markdown-server-config
  namespace: k8s-docs
  labels:
    app: markdown-server
    component: configuration
data:
  # サーバー設定
  PORT: "3000"
  NODE_ENV: "production"
  
  # ドキュメント設定
  DOCS_PATH: "/docs"
  MAX_FILE_SIZE: "10MB"
  
  # Mermaid設定
  MERMAID_THEME: "default"
  MERMAID_SECURITY_LEVEL: "loose"
  
  # アプリケーション設定
  app-config.json: |
    {
      "name": "Kubernetes学習ドキュメントサーバー",
      "version": "1.0.0",
      "description": "AWS ECS管理者向けKubernetes学習ガイド",
      "features": {
        "markdownRenderer": true,
        "mermaidSupport": true,
        "fileExplorer": true,
        "searchFunction": true
      },
      "paths": {
        "concepts": "/docs/concepts/",
        "tutorials": "/docs/tutorials/",
        "tasks": "/docs/tasks/",
        "setup": "/docs/setup/",
        "reference": "/docs/reference/"
      }
    }
