# Kubernetes学習ワークスペース - Markdown Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markdown-server
  namespace: k8s-docs
  labels:
    app: markdown-server
    component: web-server
    tier: frontend
  annotations:
    description: "Markdown & Mermaid表示サーバー"
    maintainer: "Kubernetes Learning Workspace"
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: markdown-server
  template:
    metadata:
      labels:
        app: markdown-server
        component: web-server
        tier: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/health"
    spec:
      # セキュリティコンテキスト
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      
      containers:
      - name: markdown-server
        image: k8s-markdown-server:latest
        imagePullPolicy: Never  # Minikube用設定
        
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        
        # 環境変数（ConfigMapから取得）
        envFrom:
        - configMapRef:
            name: markdown-server-config
        
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        
        # リソース制限
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # ヘルスチェック
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        
        # ボリュームマウント
        volumeMounts:
        - name: docs-volume
          mountPath: /docs
          readOnly: true
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: tmp-volume
          mountPath: /tmp
      
      # ボリューム定義
      volumes:
      - name: docs-volume
        hostPath:
          path: /docs  # minikube mount されたパス
          type: Directory
      - name: config-volume
        configMap:
          name: markdown-server-config
          items:
          - key: app-config.json
            path: app-config.json
      - name: tmp-volume
        emptyDir: {}
      
      # Pod配置制御
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - markdown-server
              topologyKey: kubernetes.io/hostname
