# Kubernetes学習ワークスペース - Markdown Server Service
apiVersion: v1
kind: Service
metadata:
  name: markdown-server-service
  namespace: k8s-docs
  labels:
    app: markdown-server
    component: web-service
  annotations:
    description: "Markdown & Mermaidサーバー用Service"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # AWS EKS用（将来拡張）
spec:
  type: NodePort  # Minikube用設定
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
    nodePort: 30080  # 外部アクセス用ポート
  selector:
    app: markdown-server
  
  # セッション維持（オプション）
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3時間

---
# ClusterIP Service (内部通信用)
apiVersion: v1
kind: Service
metadata:
  name: markdown-server-internal
  namespace: k8s-docs
  labels:
    app: markdown-server
    component: internal-service
  annotations:
    description: "内部通信専用Service"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app: markdown-server
